obj-y   += xenbus.o

xenbus-objs =
xenbus-objs += xenbus_client.o
xenbus-objs += xenbus_comms.o
xenbus-objs += xenbus_xs.o
xenbus-objs += xenbus_probe.o

#xenbus-be-objs-y += xenbus_probe_backend.o
#xenbus-objs += $(xenbus-be-objs-y)

obj-y += xenbus_probe_frontend.o
